-- create the set
INSERT INTO expansions (expansion_id, expansion_name, max_count)
VALUES ("STA", "Strixhaven: Mystical Archive", 126);

-- populate mana table
INSERT OR IGNORE INTO mana_costs (cost) VALUES
("[6][W]"), ("[G][G]"), ("[1][R]"), ("[G][U]"), ("[2][B][B]"),
("[2][U]"), ("[B]"), ("[1][W]"), ("[1][U][R]"), ("[3][B][B]"),
("[X][U][U][U]"), ("[W]"), ("[3][U][U]"), ("[3][G][G]"),
("[R]"), ("[G]"), ("[W][W]"), ("[U][U]"), ("[1][B][G]"),
("[4][U][U]"), ("[2][R]"), ("[2][G][G]"), ("[2][W]"),
("[2][G]"), ("[W][B]"), ("[1][U]"), ("[3][R]"), ("[B][B]"),
("[R][W]"), ("[1][B]"), ("[R][R]"), ("[L]"), ("[3][U/P]"),
("[U]"), ("[2][W][W]"), ("[1][G]");

-- populate with card data
INSERT INTO cards (expansion_code, card_number, card_name, mana_id, rarity) VALUES
("STA", 1, "Approach of the Second Sun", (SELECT mana_id FROM mana_costs WHERE cost = "[6][W]"), 3),
("STA", 2, "Day of Judgment", (SELECT mana_id FROM mana_costs WHERE cost = "[2][W][W]"), 3),
("STA", 3, "Defiant Strike", (SELECT mana_id FROM mana_costs WHERE cost = "[W]"), 1),
("STA", 4, "Divine Gambit", (SELECT mana_id FROM mana_costs WHERE cost = "[W][W]"), 1),
("STA", 5, "Ephemerate", (SELECT mana_id FROM mana_costs WHERE cost = "[W]"), 2),
("STA", 6, "Gift of Estates", (SELECT mana_id FROM mana_costs WHERE cost = "[1][W]"), 2),
("STA", 7, "Gods Willing", (SELECT mana_id FROM mana_costs WHERE cost = "[W]"), 2),
("STA", 8, "Mana Tithe", (SELECT mana_id FROM mana_costs WHERE cost = "[W]"), 2),
("STA", 9, "Revitalize", (SELECT mana_id FROM mana_costs WHERE cost = "[1][W]"), 1),
("STA", 10, "Swords to Plowshares", (SELECT mana_id FROM mana_costs WHERE cost = "[W]"), 2),
("STA", 11, "Teferi's Protection", (SELECT mana_id FROM mana_costs WHERE cost = "[2][W]"), 3),
("STA", 12, "Blue Sun's Zenith", (SELECT mana_id FROM mana_costs WHERE cost = "[X][U][U][U]"), 3),
("STA", 13, "Brainstorm", (SELECT mana_id FROM mana_costs WHERE cost = "[U]"), 2),
("STA", 14, "Compulsive Research", (SELECT mana_id FROM mana_costs WHERE cost = "[2][U]"), 2),
("STA", 15, "Counterspell", (SELECT mana_id FROM mana_costs WHERE cost = "[U][U]"), 2),
("STA", 16, "Memory Lapse", (SELECT mana_id FROM mana_costs WHERE cost = "[1][U]"), 2),
("STA", 17, "Mind's Desire", (SELECT mana_id FROM mana_costs WHERE cost = "[4][U][U]"), 3),
("STA", 18, "Negate", (SELECT mana_id FROM mana_costs WHERE cost = "[1][U]"), 1),
("STA", 19, "Opt", (SELECT mana_id FROM mana_costs WHERE cost = "[U]"), 1),
("STA", 20, "Strategic Planning", (SELECT mana_id FROM mana_costs WHERE cost = "[1][U]"), 1),
("STA", 21, "Tezzeret's Gambit", (SELECT mana_id FROM mana_costs WHERE cost = "[3][U/P]"), 2),
("STA", 22, "Time Warp", (SELECT mana_id FROM mana_costs WHERE cost = "[3][U][U]"), 3),
("STA", 23, "Whirlwind Denial", (SELECT mana_id FROM mana_costs WHERE cost = "[2][U]"), 1),
("STA", 24, "Agonizing Remorse", (SELECT mana_id FROM mana_costs WHERE cost = "[1][B]"), 1),
("STA", 25, "Crux of Fate", (SELECT mana_id FROM mana_costs WHERE cost = "[3][B][B]"), 3),
("STA", 26, "Dark Ritual", (SELECT mana_id FROM mana_costs WHERE cost = "[B]"), 2),
("STA", 27, "Demonic Tutor", (SELECT mana_id FROM mana_costs WHERE cost = "[1][B]"), 3),
("STA", 28, "Doom Blade", (SELECT mana_id FROM mana_costs WHERE cost = "[1][B]"), 2),
("STA", 29, "Duress", (SELECT mana_id FROM mana_costs WHERE cost = "[B]"), 1),
("STA", 30, "Eliminate", (SELECT mana_id FROM mana_costs WHERE cost = "[1][B]"), 1),
("STA", 31, "Inquisition of Kozilek", (SELECT mana_id FROM mana_costs WHERE cost = "[B]"), 2),
("STA", 32, "Sign in Blood", (SELECT mana_id FROM mana_costs WHERE cost = "[B][B]"), 2),
("STA", 33, "Tainted Pact", (SELECT mana_id FROM mana_costs WHERE cost = "[1][B]"), 3),
("STA", 34, "Tendrils of Agony", (SELECT mana_id FROM mana_costs WHERE cost = "[2][B][B]"), 2),
("STA", 35, "Village Rites", (SELECT mana_id FROM mana_costs WHERE cost = "[B]"), 1),
("STA", 36, "Chaos Warp", (SELECT mana_id FROM mana_costs WHERE cost = "[2][R]"), 3),
("STA", 37, "Claim the Firstborn", (SELECT mana_id FROM mana_costs WHERE cost = "[R]"), 1),
("STA", 38, "Faithless Looting", (SELECT mana_id FROM mana_costs WHERE cost = "[R]"), 2),
("STA", 39, "Grapeshot", (SELECT mana_id FROM mana_costs WHERE cost = "[1][R]"), 2),
("STA", 40, "Increasing Vengeance", (SELECT mana_id FROM mana_costs WHERE cost = "[R][R]"), 3),
("STA", 41, "Infuriate", (SELECT mana_id FROM mana_costs WHERE cost = "[R]"), 1),
("STA", 42, "Lightning Bolt", (SELECT mana_id FROM mana_costs WHERE cost = "[R]"), 2),
("STA", 43, "Mizzix's Mastery", (SELECT mana_id FROM mana_costs WHERE cost = "[3][R]"), 3),
("STA", 44, "Shock", (SELECT mana_id FROM mana_costs WHERE cost = "[R]"), 1),
("STA", 45, "Stone Rain", (SELECT mana_id FROM mana_costs WHERE cost = "[2][R]"), 2),
("STA", 46, "Thrill of Possibility", (SELECT mana_id FROM mana_costs WHERE cost = "[1][R]"), 1),
("STA", 47, "Urza's Rage", (SELECT mana_id FROM mana_costs WHERE cost = "[2][R]"), 2),
("STA", 48, "Abundant Harvest", (SELECT mana_id FROM mana_costs WHERE cost = "[G]"), 2),
("STA", 49, "Adventurous Impulse", (SELECT mana_id FROM mana_costs WHERE cost = "[G]"), 1),
("STA", 50, "Channel", (SELECT mana_id FROM mana_costs WHERE cost = "[G][G]"), 3),
("STA", 51, "Cultivate", (SELECT mana_id FROM mana_costs WHERE cost = "[2][G]"), 1),
("STA", 52, "Harmonize", (SELECT mana_id FROM mana_costs WHERE cost = "[2][G][G]"), 2),
("STA", 53, "Krosan Grip", (SELECT mana_id FROM mana_costs WHERE cost = "[2][G]"), 2),
("STA", 54, "Natural Order", (SELECT mana_id FROM mana_costs WHERE cost = "[2][G][G]"), 3),
("STA", 55, "Primal Command", (SELECT mana_id FROM mana_costs WHERE cost = "[3][G][G]"), 3),
("STA", 56, "Regrowth", (SELECT mana_id FROM mana_costs WHERE cost = "[1][G]"), 2),
("STA", 57, "Snakeskin Veil", (SELECT mana_id FROM mana_costs WHERE cost = "[G]"), 1),
("STA", 58, "Weather the Storm", (SELECT mana_id FROM mana_costs WHERE cost = "[1][G]"), 2),
("STA", 59, "Despark", (SELECT mana_id FROM mana_costs WHERE cost = "[W][B]"), 2),
("STA", 60, "Electrolyze", (SELECT mana_id FROM mana_costs WHERE cost = "[1][U][R]"), 2),
("STA", 61, "Growth Spiral", (SELECT mana_id FROM mana_costs WHERE cost = "[G][U]"), 2),
("STA", 62, "Lightning Helix", (SELECT mana_id FROM mana_costs WHERE cost = "[R][W]"), 2),
("STA", 63, "Putrefy", (SELECT mana_id FROM mana_costs WHERE cost = "[1][B][G]"), 2),
("STA", 64, "Approach of the Second Sun", (SELECT mana_id FROM mana_costs WHERE cost = "[6][W]"), 3),
("STA", 65, "Day of Judgment", (SELECT mana_id FROM mana_costs WHERE cost = "[2][W][W]"), 3),
("STA", 66, "Defiant Strike", (SELECT mana_id FROM mana_costs WHERE cost = "[W]"), 1),
("STA", 67, "Divine Gambit", (SELECT mana_id FROM mana_costs WHERE cost = "[W][W]"), 1),
("STA", 68, "儚い存在", (SELECT mana_id FROM mana_costs WHERE cost = "[W]"), 2),
("STA", 69, "土地の寄進", (SELECT mana_id FROM mana_costs WHERE cost = "[1][W]"), 2),
("STA", 70, "神々の思し召し", (SELECT mana_id FROM mana_costs WHERE cost = "[W]"), 2),
("STA", 71, "マナの税収", (SELECT mana_id FROM mana_costs WHERE cost = "[W]"), 2),
("STA", 72, "活力回復", (SELECT mana_id FROM mana_costs WHERE cost = "[1][W]"), 1),
("STA", 73, "剣を鍬に", (SELECT mana_id FROM mana_costs WHERE cost = "[W]"), 2),
("STA", 74, "テフェリーの防御", (SELECT mana_id FROM mana_costs WHERE cost = "[2][W]"), 3),
("STA", 75, "青の太陽の頂点", (SELECT mana_id FROM mana_costs WHERE cost = "[X][U][U][U]"), 3),
("STA", 76, "渦まく知識", (SELECT mana_id FROM mana_costs WHERE cost = "[U]"), 2),
("STA", 77, "強迫的な研究", (SELECT mana_id FROM mana_costs WHERE cost = "[2][U]"), 2),
("STA", 78, "対抗呪文", (SELECT mana_id FROM mana_costs WHERE cost = "[U][U]"), 2),
("STA", 79, "記憶の欠落", (SELECT mana_id FROM mana_costs WHERE cost = "[1][U]"), 2),
("STA", 80, "精神の願望", (SELECT mana_id FROM mana_costs WHERE cost = "[4][U][U]"), 3),
("STA", 81, "否認", (SELECT mana_id FROM mana_costs WHERE cost = "[1][U]"), 1),
("STA", 82, "選択", (SELECT mana_id FROM mana_costs WHERE cost = "[U]"), 1),
("STA", 83, "巧みな軍略", (SELECT mana_id FROM mana_costs WHERE cost = "[1][U]"), 1),
("STA", 84, "テゼレットの計略", (SELECT mana_id FROM mana_costs WHERE cost = "[3][U/P]"), 2),
("STA", 85, "時間のねじれ", (SELECT mana_id FROM mana_costs WHERE cost = "[3][U][U]"), 3),
("STA", 86, "旋風のごとき否定", (SELECT mana_id FROM mana_costs WHERE cost = "[2][U]"), 1),
("STA", 87, "苦悶の悔恨", (SELECT mana_id FROM mana_costs WHERE cost = "[1][B]"), 1),
("STA", 88, "命運の核心", (SELECT mana_id FROM mana_costs WHERE cost = "[3][B][B]"), 3),
("STA", 89, "暗黒の儀式", (SELECT mana_id FROM mana_costs WHERE cost = "[B]"), 2),
("STA", 90, "悪魔の教示者", (SELECT mana_id FROM mana_costs WHERE cost = "[1][B]"), 3),
("STA", 91, "破滅の刃", (SELECT mana_id FROM mana_costs WHERE cost = "[1][B]"), 2),
("STA", 92, "強迫", (SELECT mana_id FROM mana_costs WHERE cost = "[B]"), 1),
("STA", 93, "取り除き", (SELECT mana_id FROM mana_costs WHERE cost = "[1][B]"), 1),
("STA", 94, "コジレックの審問", (SELECT mana_id FROM mana_costs WHERE cost = "[B]"), 2),
("STA", 95, "血の署名", (SELECT mana_id FROM mana_costs WHERE cost = "[B][B]"), 2),
("STA", 96, "汚れた契約", (SELECT mana_id FROM mana_costs WHERE cost = "[1][B]"), 3),
("STA", 97, "苦悶の触手", (SELECT mana_id FROM mana_costs WHERE cost = "[2][B][B]"), 2),
("STA", 98, "村の儀式", (SELECT mana_id FROM mana_costs WHERE cost = "[B]"), 1),
("STA", 99, "混沌のねじれ", (SELECT mana_id FROM mana_costs WHERE cost = "[2][R]"), 3),
("STA", 100, "初子さらい", (SELECT mana_id FROM mana_costs WHERE cost = "[R]"), 1),
("STA", 101, "信仰無き物あさり", (SELECT mana_id FROM mana_costs WHERE cost = "[R]"), 2),
("STA", 102, "ぶどう弾", (SELECT mana_id FROM mana_costs WHERE cost = "[1][R]"), 2),
("STA", 103, "高まる復讐心", (SELECT mana_id FROM mana_costs WHERE cost = "[R][R]"), 3),
("STA", 104, "立腹", (SELECT mana_id FROM mana_costs WHERE cost = "[R]"), 1),
("STA", 105, "稲妻", (SELECT mana_id FROM mana_costs WHERE cost = "[R]"), 2),
("STA", 106, "ミジックスの熟達", (SELECT mana_id FROM mana_costs WHERE cost = "[3][R]"), 3),
("STA", 107, "ショック", (SELECT mana_id FROM mana_costs WHERE cost = "[R]"), 1),
("STA", 108, "石の雨", (SELECT mana_id FROM mana_costs WHERE cost = "[2][R]"), 2),
("STA", 109, "胸躍る可能性", (SELECT mana_id FROM mana_costs WHERE cost = "[1][R]"), 1),
("STA", 110, "ウルザの激怒", (SELECT mana_id FROM mana_costs WHERE cost = "[2][R]"), 2),
("STA", 111, "豊穣な収穫", (SELECT mana_id FROM mana_costs WHERE cost = "[G]"), 2),
("STA", 112, "冒険の衝動", (SELECT mana_id FROM mana_costs WHERE cost = "[G]"), 1),
("STA", 113, "チャネル", (SELECT mana_id FROM mana_costs WHERE cost = "[G][G]"), 3),
("STA", 114, "耕作", (SELECT mana_id FROM mana_costs WHERE cost = "[2][G]"), 1),
("STA", 115, "調和", (SELECT mana_id FROM mana_costs WHERE cost = "[2][G][G]"), 2),
("STA", 116, "クローサの掌握", (SELECT mana_id FROM mana_costs WHERE cost = "[2][G]"), 2),
("STA", 117, "自然の秩序", (SELECT mana_id FROM mana_costs WHERE cost = "[2][G][G]"), 3),
("STA", 118, "原初の命令", (SELECT mana_id FROM mana_costs WHERE cost = "[3][G][G]"), 3),
("STA", 119, "新たな芽吹き", (SELECT mana_id FROM mana_costs WHERE cost = "[1][G]"), 2),
("STA", 120, "蛇皮のヴェール", (SELECT mana_id FROM mana_costs WHERE cost = "[G]"), 1),
("STA", 121, "嵐の乗り切り", (SELECT mana_id FROM mana_costs WHERE cost = "[1][G]"), 2),
("STA", 122, "灯の燼滅", (SELECT mana_id FROM mana_costs WHERE cost = "[W][B]"), 2),
("STA", 123, "電解", (SELECT mana_id FROM mana_costs WHERE cost = "[1][U][R]"), 2),
("STA", 124, "成長のらせん", (SELECT mana_id FROM mana_costs WHERE cost = "[G][U]"), 2),
("STA", 125, "稲妻のらせん", (SELECT mana_id FROM mana_costs WHERE cost = "[R][W]"), 2),
("STA", 126, "化膿", (SELECT mana_id FROM mana_costs WHERE cost = "[1][B][G]"), 2);
